# Use an official Golang runtime as a parent image
FROM golang:1.21.1

# Set the working directory to /chaincode
WORKDIR /chaincode

# Copy the current directory contents into the container at /chaincode
COPY . /chaincode

# Build the chaincode
RUN go build -o run

# Specify the command to run on container start
CMD ["./run"]
