apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ca
  labels:
    volume: ca
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /root/ca
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - chp-srvaida69