apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-ca
  storageClassName: standard