apiVersion: v1
kind: Service
metadata:
  name: ca
spec:
  selector:
    service: ca
  ports:
    - protocol: TCP
      name: tcp
      port: 7054
      targetPort: 7054
      nodePort: 30007
  type: NodePort
