apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-orgy-couch-peer1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-orgy-couch-peer1
  storageClassName: standard