apiVersion: v1
kind: Service
metadata:
  name: orgy-couch-peer1
  labels:
    peer-parent: orgy-peer1
    type-component: couch
    name-component: orgy-couch-peer1
    msp: OrgyMSP
spec:
  selector:
    service: orgy-couch-peer1
  ports:
    - protocol: TCP
      name: tcp
      port: 80
      targetPort: 5984
  type: ClusterIP