apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-orgz-orderer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-orgz-orderer
  storageClassName: standard