apiVersion: v1
kind: Service
metadata:
  name: orgz-orderer
  labels:
    type-component: orderer
    name-component: orgz-orderer
    msp: OrgzMSP
spec:
  selector:
    service: orgz-orderer
  ports:
    - protocol: TCP
      name: tcp
      port: 80
      targetPort: 7777
      nodePort: 30015
    - protocol: TCP
      name: tcp-admin-port
      port: 81
      targetPort: 9006
      nodePort: 30044
    - protocol: TCP
      name: tcp-grpc-automation-project
      port: 82
      targetPort: 2000
      nodePort: 30045
    - protocol: TCP
      name: operations
      port: 83
      targetPort: 9004
      nodePort: 30052
  type: NodePort
