apiVersion: v1
kind: Service
metadata:
  name: block-explorer
spec:
  selector:
    service: block-explorer
  ports:
    - protocol: TCP
      targetPort: 5432
      port: 80
      name: tcp
  type: ClusterIP
