apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-orgx-peer1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-orgx-peer1
  storageClassName: standard
