apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    service: prometheus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      name: tcp
      nodePort: 30019
  type: NodePort
