apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test-communication
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /run/media/pedromn35/disk2-home/projects/hospital-installation-kubernetes/Future-incrementations/kubernetes-automation-deployment/go-communication-inside
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - pedromn35-gf63thin9sc