apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-communication
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-test-communication
  storageClassName: standard
