apiVersion: apps/v1
kind: Deployment
metadata:
  name: orgy-peer1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: orgy-peer1
  template:
    metadata:
      labels:
        deployment: orgy-peer1
        service: orgy-peer1
    spec:
      containers:
        - name: orgy-peer1-container
          image: hyperledger/fabric-peer
          env:
            - name: FABRIC_CFG_PATH
              value: "/tmp/hyperledger/orgy-peer1/config"
          volumeMounts:
            - mountPath: "/tmp/hyperledger/orgy-peer1/"
              name: orgy-peer1-volume
            - mountPath: "/var/run"
              name: orgy-peer1-volume-container-runtime
      volumes:
        - name: orgy-peer1-volume
          persistentVolumeClaim:
            claimName: pvc-orgy-peer1
