apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-orgx-couch-peer1
  labels:
    volume: orgx-couch-peer1
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /run/media/pedromn35/disk2-home/projects/LoadBalancingLocally/kubernetes/practical/hlf-premise/hlf-components-config/orgx-peer1-couch
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - pedromn35-gf63thin9sc