apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-orgx-couch-peer1
  labels:
    volume: orgx-couch-peer1
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /root/orgx-couch-peer1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - chp-srvaida69
