apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc.dep.y.couch.peer1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv.dep.y.couch.peer1
  storageClassName: standard