apiVersion: apps/v1
kind: Deployment
metadata:
  name: tls-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: tls-ca
  template:
    metadata:
      labels:
        deployment: tls-ca
        service: tls-ca
    spec:
      containers:
        - name: tls-ca-container
          image: hyperledger/fabric-ca
          volumeMounts:
            - mountPath: "/etc/hyperledger/fabric-ca-server"
              name: tls-ca-volume
      volumes:
        - name: tls-ca-volume
          persistentVolumeClaim:
            claimName: pvc-tls-ca
