apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tls-ca
  labels:
    volume: tls-ca
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /root/tls-ca
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - chp-srvaida69
