apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tls-ca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-tls-ca
  storageClassName: standard
