apiVersion: v1
kind: Service
metadata:
  name: tls-ca
spec:
  selector:
    service: tls-ca
  ports:
    - protocol: TCP
      name: tcp
      port: 7054
      targetPort: 7054
      nodePort: 30008
  type: NodePort
