apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-postgresql-block-explorer
  labels:
    volume: db-postgresql-block-explorer
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /root/db-postgresql-block-explorer
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - chp-srvaida69