apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db-postgresql-block-explorer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-db-postgresql-block-explorer
  storageClassName: standard
