apiVersion: v1
kind: Service
metadata:
  name: quarkus-rest-hlf-network
spec:
  selector:
    service: quarkus-rest-hlf-network
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
      name: tcp
      nodePort: 30020
  type: NodePort
