apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-orgy-orderer
  labels:
    volume: orgy-orderer
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /root/orgy-orderer
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - chp-srvaida70
