apiVersion: v1
kind: Service
metadata:
  name: hlf-network
spec:
  selector:
    global-service: peer-load-balancing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7777
  type: LoadBalancer
