apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    service: keycloak
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: tcp
      nodePort: 30020
  type: NodePort
