apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-orgx-orderer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-orgx-orderer
  storageClassName: standard